Mqtt support
dreadnought/python-daly-bms pull request #8
Opened 2021-08-14 03:16 UTC by brendanjerwin

I'm no python dev but this is working for me.

2021-08-20 08:27 UTC, dreadnought requested changes

2021-08-20 08:27 UTC, dreadnought commented on bin/daly-bms-cli
> +import paho.mqtt.client as paho
That's here the only thing that I would change in your pull request. As not everyone will use MQTT, I would rather make it optional than forcing everyone to install the dependency.

You can find an example here: https://github.com/dreadnought/python-daly-bms/blob/main/dalybms/__init__.py

But instead of `pass` I would set `paho = None`, so that you can check it later in the code where you do `if args.mqtt:` and print an error and exit in case it's not installed but the argument was set.

2021-08-29 08:32 UTC, birdie1 commented
Looking forward to use mqtt for integration for my homeassistant. 

Tested this and found a little bug: `--all` does not work together with `--mqtt`. If mqtt is active, it will iterate only over the first depth of dict and tries to send a dict via mqtt which ends as error. It either must iterate the second depth as well or do a json.dumps()

2021-09-19 18:13 UTC, dreadnought commented
The development continues in #13.

2021-09-19 18:13 UTC, closed without merging